import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway, Figtree, Noto_Sans, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { ThemeProvider } from "@/components/themeprovider";

import AppSidebar from "@/components/ui/appsidebar";
import { cn } from "@/lib/utils";
import {AuthProvider} from "@/contexts/authContext";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
const interHeading = Inter({subsets:['latin'],variable:'--font-heading'});

const notoSans = Noto_Sans({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Luxavian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html 
  lang="en"
  suppressHydrationWarning
  className={cn(
    "font-sans",
    notoSans.variable,
    interHeading.variable
  )}
>
    <body className="min-h-screen bg-background font-sans text-foreground antialiased">
    
    <AuthProvider>
      <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      
              
       <SidebarProvider defaultOpen={false}>
      
        
    
     
        
<AppSidebar/>
        <main className='flex-1' >
          
            
           <Navbar />
          {children}
        
        </main>
      
    

        
       </SidebarProvider>

     

    </ThemeProvider>
    </AuthProvider>

  </body>
 
</html>
  );
}
